# Config file for automatic testing at travis-ci.org

language: python

before_script:
  - sleep 3

python:
  - "3.6"

# Command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pylint

# Command to run tests
script:
  - pylint avand_garte/*py
  - pytest
